### ISSUE TITLE
Usage of Twint

### ISSUE THREAD

**Issue by DonaldTsang** [alumbreras/twitter-followers-graph#6]
There is no limit on API within Twint https://github.com/twintproject/twint might be a good idea to use it in our favor

**Comment by DonaldTsang** [comment]
Other alternatives that tried to get Twitter followers:
- https://github.com/karpathy/find-birds
- https://github.com/ducu/twitter-most-followed
- https://github.com/ChunaraLab/Fetching-Twitter-Followers

**Comment by alumbreras** [comment]
Thanks for the pointer! But Twint is a scraper, I prefer respecting the API (for now), though.
